
make distclean
find * | grep "\.o$" | xargs rm
./configure --prefix=./zyl/arm64 --arch=arm64 --cpu=armv8 --target-os=darwin --enable-optimizations --enable-asm --disable-armv5te --enable-lto --enable-cross-compile --enable-pic --disable-debug --disable-logging --disable-programs --disable-doc --disable-runtime-cpudetect --enable-version3 --disable-symver --disable-iconv --disable-bzlib --disable-zlib --disable-avdevice --disable-everything --enable-bsf=h264_mp4toannexb --enable-swscale --enable-network --enable-protocol=file --enable-protocol=http --enable-protocol=rtmp --enable-protocol=hls --enable-demuxer=hls --enable-demuxer=mpegts --enable-demuxer=mov --enable-demuxer=flv --enable-muxer=mp4 --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=aac --enable-encoder=aac --enable-parser=h264 --sysroot="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk" --cc="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" --extra-cflags="-w -arch arm64 -mfpu=neon -miphoneos-version-min=8.0" --extra-cxxflags="-w -arch arm64 -mfpu=neon -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk" --extra-ldflags="-arch arm64 -mfpu=neon -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/usr/lib/system" --sysinclude="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/usr/include/"
make
make install

make distclean
find * | grep "\.o$" | xargs rm
./configure --prefix=./zyl/armv7 --arch=armv7 --cpu=cortex-a8 --target-os=darwin --enable-optimizations --enable-asm --disable-armv5te --enable-lto --enable-cross-compile --enable-pic  --disable-debug --disable-logging --disable-programs --disable-doc --disable-runtime-cpudetect --enable-version3 --disable-symver --disable-iconv --disable-bzlib --disable-zlib --disable-avdevice --disable-everything --enable-bsf=h264_mp4toannexb --enable-swscale --enable-network --enable-protocol=file --enable-protocol=http --enable-protocol=rtmp --enable-protocol=hls --enable-demuxer=hls --enable-demuxer=mpegts --enable-demuxer=mov --enable-demuxer=flv --enable-muxer=mp4 --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=aac --enable-encoder=aac --enable-parser=h264 --sysroot="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk" --cc="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" --extra-cflags="-w -arch armv7 -mfpu=neon -miphoneos-version-min=8.0" --extra-cxxflags="-w -arch armv7 -mfpu=neon -miphoneos-version-min=8.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk" --extra-ldflags="-arch armv7 -mfpu=neon -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/usr/lib/system" --sysinclude="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/usr/include/"
make
make install

xcrun --sdk iphoneos lipo -output zyl/libavcodec.a -create zyl/armv7/lib/libavcodec.a zyl/arm64/lib/libavcodec.a
xcrun --sdk iphoneos lipo -output zyl/libavfilter.a -create zyl/armv7/lib/libavfilter.a zyl/arm64/lib/libavfilter.a
xcrun --sdk iphoneos lipo -output zyl/libavformat.a -create zyl/armv7/lib/libavformat.a zyl/arm64/lib/libavformat.a
xcrun --sdk iphoneos lipo -output zyl/libavutil.a -create zyl/armv7/lib/libavutil.a zyl/arm64/lib/libavutil.a
xcrun --sdk iphoneos lipo -output zyl/libswresample.a -create zyl/armv7/lib/libswresample.a zyl/arm64/lib/libswresample.a
xcrun --sdk iphoneos lipo -output zyl/libswscale.a -create zyl/armv7/lib/libswscale.a zyl/arm64/lib/libswscale.a


make distclean
find * | grep "\.o$" | xargs rm
./configure --prefix=./zyl/android --arch=armv7 --cpu=cortex-a8 --target-os=linux --enable-optimizations --enable-asm --disable-armv5te --enable-lto --enable-cross-compile --enable-pic --disable-debug --disable-logging --disable-programs --disable-doc --disable-runtime-cpudetect --enable-version3 --disable-symver --disable-iconv --disable-bzlib --disable-zlib  --disable-avdevice --disable-everything --enable-bsf=h264_mp4toannexb --enable-swscale --enable-network --enable-protocol=file --enable-protocol=http --enable-protocol=rtmp --enable-protocol=hls --enable-demuxer=hls --enable-demuxer=mpegts --enable-demuxer=mov --enable-demuxer=flv --enable-muxer=mp4 --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=aac --enable-encoder=aac --enable-parser=h264 --sysroot="/opt/android/ndk/platforms/android-15/arch-arm/"  --sysinclude="/opt/android/ndk/platforms/android-15/arch-arm/usr/include/" --cross-prefix="/opt/android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-" --extra-cflags="-w -mvectorize-with-neon-quad -mfpu=neon -mfloat-abi=softfp" --extra-ldflags="-mfpu=neon -L/opt/android/ndk/platforms/android-15/arch-arm/usr/lib -nostdlib /opt/android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.8/crtbegin.o /opt/android/ndk/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.8/crtend.o -lc -lm"
make
make install
